name: "🐛 Bug Report"
description: Report an issue with InfraBox
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      value: |
        1. Go to '...'
        2. Run '...'
        3. See error

  - type: input
    id: version
    attributes:
      label: CLI version
      description: Output of `python InfraBox.py --version` (if applicable)

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Linux
        - macOS
        - Windows
