name: "✨ Feature Request"
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A concise description of what you'd like to see.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      description: Help us understand the context.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Are there other solutions you've considered?
